### ISSUE TITLE
2.3.0 Checklist

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#1830]
## 2.3.0 (September 28, 2016)
* Documentation:
  - [x] Finish Component-to-Utility Migration (~~FRMW-772~~)
* Source Code:
  - [x] normalize to `ng-disabled` instead of `disabled` to take advantage of ngAria functionality (FRMW-717)
  - [x] Add filters to implement date/time formats (FRMW-817) _(v2.1.0)_
  - [x] Add rxCopy directive for one-click copy to clipboard functionality (FRMW-455)
* Design:
  - [x] Add `:focus` styling for form elements (FRMW-566)
* Back End:
  - [x] stop publishing to CDN (FRMW-968) _(v2.2.0)_
  - [x] fix/improve/kill CHANGELOG.md (FRMW-967)
* rxPageObjects:
  - [x] add `rxActionMenu.isPresent()` _(v2.2.0)_
