### ISSUE TITLE
Framework Feature Adoption Process/Checklist

### ISSUE THREAD

**Issue by TheNando** [rackerlabs/encore-ui#1849]
Part of the move to bringing each app into Origin as a first-class citizen will be sorting through each application's unique functionality, determining if it belongs at the app level or at the framework level. In some cases, apps may have app-level features or functionality that are redundant to those found in other apps or to the framework's. Or perhaps they have imported a framework feature into the app's library to make customizations.

In any case, this is a good opportunity to formalize a path to graduate a feature from being app-specific to being included in the framework, where other apps may benefit from it.

I spent some time discussing this with @jgonz0010, and @CITguy. I created a WIP checklist below. Let's discuss what to add/change/remove to come up with an official **Framework Feature Adoption Process** that may be shared with other project teams.

 - [ ] Approval
    - [ ] Design
    - [ ] Framework
 - [ ] Functionality
    - [ ] Generalized - Feature should be generalized or generic, not including any app-specific or Rackspace-specific logic/references
    - [ ] Reusable - Feature should support multiple use cases
    - [ ] Applicable - Feature should address needs across more than one application
- [ ] Standards/Quality
    - [ ] Style and patterns
    - [ ] Unit Test Coverage
    - [ ] Functional Test Coverage
    - [ ] Page object helpers
    - [ ] Documentation
 - [ ] Process
    - [ ] Design Approval
    - [ ] Released in production at App level
    - [ ] Working in production for X amount of time
    - [ ] Begin adoption into Framework
    - [ ] ?
    - [ ] Feature Released
    - [ ] Application updated to remove local instance/add framework instance

**Comment by CITguy** [comment]
Closing. Will not complete due to change of direction in UIs.
